---
apiVersion: v1 # Kubernetes API version
kind: ConfigMap # Kubernetes ConfigMap kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: merchants-dev-config-kubernetes
#  name: cards-g
data:
  application-kubernetes.yml: |-
    server.port: "8093"
    spring.profiles.active: kubernetes
    pp.paynet.baseurl: http://paynet-adapter-dev-service:8094
    bean.message: "Testing reload! Message from backend is: %s <br/> Services : %s"
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: merchants-dev-service
spec:
  selector:
    app: merchants-dev-app
  ports:
    - protocol: "TCP"
      port: 8093 # The port that the service is running on in the cluster
      targetPort: 8093 # The port exposed by the service
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: merchants-dev-app
spec:
  selector:
    matchLabels:
      app: merchants-dev-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: merchants-dev-app
        environment: development
        tier: backend
        release: canary
        owner: denizz
    spec:
      containers:
        - name: merchants-dev-app
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          # - name: SPRING_PROFILES_ACTIVE
            # value: dev
#          - name: SPRING_DATASOURCE_URL
#            valueFrom:
#              configMapKeyRef: # env from ConfigMap
#                name: cards-gw
#                key: spring.datasource.url
#          - name: SERVER_PORT
#            valueFrom:
#              configMapKeyRef: # env from ConfigMap
#                name: cards-gw
#                key: server.port
#          - name: UZCARD_GW_SERVICE_URI
#            value: http://uzcard-gw-dev-service
#          - name: HUMO_GW_SERVICE_URI
#            value: http://humo-gw-dev-service
          - name: SPRING_DATASOURCE_PASSWORD
            value: P3plat123
          image: episodeone/merchants-dev:0.1.0
          # imagePullPolicy: Always
          # livenessProbe:
            # httpGet:
              # path: /actuator/health
              # port: 8195
            # initialDelaySeconds: 40
            # timeoutSeconds: 6
            # periodSeconds: 60
            # failureThreshold: 3
          # readinessProbe:
            # httpGet:
              # path: /actuator/health
              # port: 8195
            # initialDelaySeconds: 40
            # timeoutSeconds: 6
            # periodSeconds: 60
            # failureThreshold: 3
#          resources:
#            requests:
#              memory: "1024Mi"
#              cpu: "500m"
#            limits:
#              memory: "1536Mi"
#              cpu: "2000m"
          ports:
            - containerPort: 8093 # The port that the container is running on in the cluster
